######################################### ???
IMAGE_FILE_PATH=/apps/bakelab/save_images/
SAVE_PATH=/apps/bakelab/save_images
LOCAL_IMAGE_FILE_PATH=C:\\bakelab\\save_images\\
LOCAL_SAVE_PATH=C:\\bakelab\\save_images